#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars

mkdir -p /var/log/mysql
chown -R mysql:mysql /var/log/mysql

chown -R mysql:mysql /var/lib/mysql
if [ ! -f /var/lib/mysql/ibdata1 ]; then
   mysqld --initialize-insecure
fi

exec 2>&1
exec /usr/bin/mysqld_safe --skip-syslog
