#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars

mkdir -p /var/log/mysql
chown -R mysql:mysql /var/log/mysql

if [ ! "$(ls -A /var/lib/mysql/ibdata1)" ]; then
   mysqld --initialize-insecure
   chown -R mysql:mysql /var/lib/mysql

   /usr/bin/mysqld_safe --skip-syslog & 
   mysqladmin --wait=5 ping
   mysql < /usr/share/mysql/innodb_memcached_config.sql
   mysql < /mysql.ddl
   mysqladmin shutdown
fi

chown -R mysql:mysql /var/lib/mysql

exec 2>&1
exec /usr/bin/mysqld_safe --skip-syslog
